seed: 42
size: 'ExtraSmall'

base_size: 512
metric: accuracy


train_conf:
  run_name: base_resnet_50_pretrained
  lr: 0.001
  batch_size: 256
  gradient_accumulation_steps: 1
  eval_batch_size: 512
  max_steps: 50000
  warmip_ratio: 0.1
  eval_freq: 5
  log_freq: 5
  save_freq: 5