seed: 42
size: 'Regular'
model: 'microsoft/resnet-50'

base_size: 224
metric: accuracy


train_conf:
  run_name: base_resnet_50_pretrained
  lr: 0.001
  batch_size: 16
  gradient_accumulation_steps: 1
  eval_batch_size: 16
  max_steps: 1500
  warmip_ratio: 0.1
  eval_freq: 50
  save_freq: 500
  log_freq: 1
  save_freq: 10000
  report_to: comet_ml
  dataloader_num_workers: 24