seed: 42
size: 'ExtraSmall'
model: 'microsoft/resnet-50'

base_size: 224
metric: accuracy


train_conf:
  run_name: base_resnet_50_pretrained
  lr: 0.001
  batch_size: 64
  gradient_accumulation_steps: 1
  eval_batch_size: 128
  max_steps: 2000
  warmip_ratio: 0.1
  eval_freq: 100
  save_freq: 500
  log_freq: 1
  report_to: comet_ml
  dataloader_num_workers: 16